export const ARTICLE_PUBLISH = "publishArticle";
export const ARTICLE_DELETE = "deleteArticle";
export const ARTICLE_EDIT = "editArticle";
export const ARTICLE_RESET_STATE = "resetArticleState";
export const CHECK_AUTH = "checkAuth";
export const FETCH_ARTICLE = "fetchArticle";
export const FETCH_ARTICLES = "fetchArticles";
export const FETCH_AUTH_ARTICLES = "fetchAuthArticles";
export const RATINGS_CREATE = "createRating";
export const FETCH_USER_ARTICLES = "fetchUserArticles";
export const FETCH_RATINGS = "fetchRatings";
export const FETCH_CATEGORII = "fetchCategorii";
export const CREATE_CATEGORII = "createCategorii";
export const LOGIN = "login";
export const LOGOUT = "logout";
export const REGISTER = "register";
export const UPDATE_USER = "updateUser";
export const FETCH_CURRENTUSER_ARTICLE="fetchCurrentUserPost"
