export const FETCH_END = "setArticles";
export const FETCH_START = "setLoading";
export const FETCH_USER_END = "setUserArticles";
export const FETCH_USER_START = "setUserLoading";
export const PURGE_AUTH = "logOut";
export const SET_ARTICLE = "setArticle";
export const SET_AUTH = "setUser";
export const SET_USER='setAuthUser'
export const SET_RATINGS = "setRatings";
export const SET_ERROR = "setError";
export const SET_LOADING = "setLoading";
export const UNSET_LOADING = "unsetLoading";
export const SET_PROFILE = "setProfile";
export const UPDATE_ARTICLE_IN_LIST = "updateArticleInList";
export const RESET_STATE = "resetModuleState";
export const FETCH_DELETE_END = "fetchDeleteEnd";
export const FETCH_CATEGORII_END = "fetchCategoriiEnd";
